# Generated by Django 5.2.5 on 2025-08-25 13:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0002_produit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='reference',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=50, unique=True),
        ),
    ]
