# Generated by Django 5.2.5 on 2025-08-25 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0003_alter_produit_reference'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Commande',
        ),
    ]
