# Generated by Django 5.2.5 on 2025-08-26 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0004_delete_commande'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Produit',
            new_name='Product',
        ),
    ]
